# Generated by Django 3.1 on 2020-08-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101, verbose_name='title')),
                ('mix', models.CharField(max_length=7)),
                ('has_prew', models.BooleanField(default=False)),
                ('has_mp4', models.BooleanField(default=False)),
                ('has_webm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('title', 'mix'), name='no_duplicate'),
        ),
    ]
